advanced/common/models/Subscribes.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "subscribes".
 *
 * @property int $id
 * @property string $email_user
 * @property int|null $status
 * @property int|null $created_at
 */
class Subscribes extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'subscribes';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['email_user'], 'required'],
            [['status', 'created_at'], 'integer'],
            [['email_user'], 'string', 'max' => 255],
            [['email_user'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email_user' => 'Email User',
            'status' => 'Status',
            'created_at' => 'Created At',
        ];
    }
}

advanced/backend/controllers/SubscribesController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Subscribes;
use common\models\search\SubscribesSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SubscribesController implements the CRUD actions for Subscribes model.
 */
class SubscribesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [

                    [
//                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        // your custom code here, if you want the code to run before action filters,
        // which are triggered on the [[EVENT_BEFORE_ACTION]] event, e.g. PageCache or AccessControl

        if (!parent::beforeAction($action)) {
            return false;
        }

        // other custom code here

        return true; // or false to not run the action
    }


    /**
     * Lists all Subscribes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SubscribesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Subscribes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Subscribes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Subscribes();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Subscribes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Subscribes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Subscribes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Subscribes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Subscribes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

advanced/frontend/controllers/SubscribeController.php
<?php


namespace frontend\controllers;


use frontend\models\forms\SubscribeForm;
use Yii;
use yii\filters\AccessControl;

class SubscribeController extends AppController
{


    public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'roles' => ['@'],
                        'allow' => true,
                    ],

                ],
            ],


        ];
    }

    public function actionIndex() {


        $model = new SubscribeForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $summa = self::calcSumma($model->count_mounths);
            $session = Yii::$app->session;
            $session->set('add_balance', $summa);
            $session->set('period', $model->count_mounths);


            if ($model->cashbox == 1 ) { return $this->redirect('/interkassa/index');  }
            if ($model->cashbox == 2 ) { return $this->redirect('/freekassa/index');  }
            if ($model->cashbox == 3) { return $this->redirect('/primepayments/index');  }







        }

        return $this->render('index', [
            'model' => $model,
        ]);


    }

    public function actionGetPrice($id) {

        $id = (int) $id;

        if ($id < 12) { $price = $id*9.99; }
        if ($id == 12) { $price = 72; }
        if ($id == 13) { $price = 200; }


        echo "<br>";
        echo "Стоимость: "; echo $price; echo "USD";

        echo "<br>";  echo "<br>";

        die();


    }

    public  static function calcSumma($id) {
        $id = (int) $id;

        if ($id < 12) { $price = $id*9.99; }
        if ($id == 12) { $price = 72; }
        if ($id == 13) { $price = 200; }

        return $price;




    }
    

}

advanced/frontend/controllers/SubscribesController.php
<?php

namespace frontend\controllers;

use common\models\Subscribes;
use frontend\models\forms\SubscribeForm;
use Yii;

class SubscribesController extends AppController
{
    public function beforeAction($action)
    {
        if (in_array($action->id, ['add'  ])) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }


    public function actionAdd()
    {

        if (isset($_POST["EMAIL"])) {
        $insert_email = new Subscribes();
        $insert_email->email_user = $_POST["EMAIL"];
            $insert_email->status = 10;
            $insert_email->created_at = time();
            $insert_email->save();
            Yii::$app->session->setFlash('success', "Спасибо.  Вы подписаны на рассылку.");

        }



        return $this->render('add');
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

}

advanced/frontend/views/subscribe/index.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\captcha\Captcha;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Alert;



$this->title = 'Оформить подписку ';
$this->params['breadcrumbs'][] = $this->title;
?>

<h3>Оформить подписку</h3>

<script>
    $(document).ready(function(){

        // alert(jQuery.fn.jquery);



        $('select').on('change', function() {
            // alert( this.value );
            var count_mounth = this.value;
            $('#itogo').empty();

            $.ajax({
                type: 'GET',
                url: '/subscribe/get-price',
                data: {id:count_mounth},
                success: function (html) {
                    $("#itogo").append(html);
                }
            });   /////////// AJAX POST


        });



    });
</script>


<div class="row">
    <div class="col-lg-5">
        <?php $form = ActiveForm::begin(['id' => 'subscribe']); ?>

        <?php

        echo $form->field($model, 'count_mounths')->dropDownList([

            '' => 'Выберите...',
            '1' => '1 месяц',
            '2' => '2 месяца',
            '3'=>'3 месяца',
            '4'=>'4 месяца',
            '5'=>'5 месяцев',
            '6'=>'6 месяцев',
            '7'=>'7 месяцев',
            '8'=>'8 месяцев',
            '9'=>'9 месяцев',
            '10'=>'10 месяцев',
            '11'=>'11 месяцев',
            '12'=>'1 год',
            '13'=>'Вечный аккаунт',
        ]);

        ?>
        <div id="itogo" style="font-size: 22px; color: green; font-weight: 700;"></div>


        <?php

        echo $form->field($model, 'cashbox')->dropDownList([

//            '1' => 'Interkassa',
            '2' => 'Freekassa',
//            '3' => 'Primepayments',

        ]);

        ?>



            <?= Html::submitButton('Оплатить', ['class' => 'stm-btn stm-btn_outline stm-btn_orange stm-btn_md', 'name' => 'contact-button']) ?>


        <?php ActiveForm::end(); ?>
    </div>
</div>