advanced/frontend/controllers/PlayWordsController.php
<?php


namespace frontend\controllers;


use common\models\PlayList;
use common\models\Playlistwords;
use common\models\Words;
use Yii;
use yii\filters\AccessControl;

class PlayWordsController extends AppController
{


    public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'roles' => ['@'],
                        'allow' => true,
                    ],

                ],
            ],


        ];
    }


    public function beforeAction($action)
    {
        if (in_array($action->id, ['next-word' , 'count-progress-bar' , 'prev-word' , 'to-the-begining' , 'mix-and-start' , 'learn-and-del'  ])) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }


    public function actionIndex()
    {

        $request = Yii::$app->request;

        $list = $request->get('list');
        $get_list_name = PlayList::findOne($list);

        $list = (int) $list;
        $word_id = AjaxStaticFunctionController::getCurrentWordForIndex($list);
        $select_word = Words::findOne($word_id);
        return $this->render('index',
            [
                'select_word' => $select_word,
                'get_list_name' => $get_list_name,
            ]
        );


    }

    public function actionNextWord()
    {


        $request = Yii::$app->request;
        $list_id = $request->post('id');



        $list_id = (int)$list_id;
        $word_id = AjaxStaticFunctionController::getCurrentWord($list_id);
        $select_word = Words::findOne( $word_id );
//        $select_word =  json_encode( $select_word);
//        print_r($select_word);
        $json = AjaxStaticFunctionController::preparationData($select_word);
        header('Content-type: application/json');
        echo $json;
        exit;


    }


    public function actionPrevWord()
    {
        $request = Yii::$app->request;
        $list_id = $request->post('id');
        $list_id = (int)$list_id;
        $word_id = AjaxStaticFunctionController::getCurrentWordForPrev($list_id );
        $select_word = Words::findOne( $word_id );
//        $select_word =  json_encode( $select_word);
//        print_r($select_word);
        $json = AjaxStaticFunctionController::preparationData($select_word);
        header('Content-type: application/json');
        echo $json;
        exit;


    }

    public function actionToTheBegining()
    {
        $request = Yii::$app->request;
        $list_id = $request->post('id');
        $list_id = (int)$list_id;
        $word_id = AjaxStaticFunctionController::getCurrentWordForBegin($list_id );
        $select_word = Words::findOne( $word_id );
//        $select_word =  json_encode( $select_word);
//        print_r($select_word);
        $json = AjaxStaticFunctionController::preparationData($select_word);
        header('Content-type: application/json');
        echo $json;
        exit;


    }


    public function actionLearnAndDel()
    {
        $request = Yii::$app->request;
        $list_id = $request->post('id');
        $list_id = (int)$list_id;
        $word_id = AjaxStaticFunctionController::getCurrentWordForLearnAndDel($list_id );
        $select_word = Words::findOne( $word_id );
//        $select_word =  json_encode( $select_word);
//        print_r($select_word);
        $json = AjaxStaticFunctionController::preparationData($select_word);
        header('Content-type: application/json');
        echo $json;
        exit;


    }


    public function actionMixAndStart()
    {
        $request = Yii::$app->request;
        $list_id = $request->post('id');
        $list_id = (int)$list_id;
        $word_id = AjaxStaticFunctionController::getCurrentWordForMixAndStart($list_id );
        $select_word = Words::findOne( $word_id );
//        $select_word =  json_encode( $select_word);
//        print_r($select_word);
        $json = AjaxStaticFunctionController::preparationData($select_word);
        header('Content-type: application/json');
        echo $json;
        exit;


    }

    public function actionCountProgressBar()
    {

        $request = Yii::$app->request;
        $list_id = $request->post('id');
        $list_id = (int)$list_id;

        $procent = AjaxStaticFunctionController::countProgressBar($list_id);
        header('Content-type: application/json');
        echo $procent;
        exit;

    }

    public function actionExercises2() {





    }








}

advanced/frontend/views/play-words/insert_js.php
<script>

    $(document).ready(function () {
        function empty_blocks() {

            $("#word,#transcription,#translate,#translation_options,#examples,#definitions").empty()
            // alert('reload cart called');
        }

        function countprogressbar() {

            $.ajax({
                type: 'POST',
                url: '/play-words/count-progress-bar',
                data: {id: '<?php echo $list_id; ?>'},
                success: function (data) {
                    // const parseData = JSON.parse(data);
                    $(".vc_bar_val").html(data + "%");
                    $('.vc_bar').attr('data-percentage-value', data);
                    $('.vc_bar').attr('style', "min-width: 3em; width: " + data + "%;");
                    $('.vc_bar').attr('data-value', data);


                }
            });

        }

        countprogressbar();


        function fill_blocks(respond_my) {
            countprogressbar();


            $("#word").html(respond_my[1]);

            if (respond_my[2] != null) {
                $("#transcription").css("display", "block");
                $("#transcription").html('[' + respond_my[2] + ']');
            } else {
                $("#transcription").css("display", "none");
            }


            $("#translate").html(respond_my[5]);

            if (respond_my[12] != "") {
                $("#trans_wrap").css("display", "block");
                $("#translation_options").html(respond_my[12]);
            } else {
                $("#trans_wrap").css("display", "none");
            }

            if (respond_my[13] != "") {
                $("#ex_wrap").css("display", "block");
                $("#examples").html(respond_my[13]);
            } else {
                $("#ex_wrap").css("display", "none");
            }

            if (respond_my[14] != "") {
                $("#def_wrap").css("display", "block");
                $("#definitions").html(respond_my[14]);
            } else {
                $("#def_wrap").css("display", "none");
            }

            // $("#examples").html(respond_my[13]);
            // $("#definitions").html(respond_my[14]);


            // console.log(respond_my);

        }

        function return_ajax(respond_my) {
            empty_blocks();
            fill_blocks(respond_my);


        }


        $("#next").click(function () {
            // $("span#itogo").empty();
            //     var param = $('meta[name="csrf-param"]').attr("content");
            //     var token = $('meta[name="csrf-token"]').attr("content");

            $.ajax({
                type: 'POST',
                url: '/play-words/next-word',
                dataType: 'json',
                data: {id: '<?php echo $list_id; ?>'},
                success: function (data) {
                    // const parseData = JSON.parse(data);
                    return_ajax(data);


                }
            });
        })


        $("#prev").click(function () {
            // $("span#itogo").empty();

            $.ajax({
                type: 'POST',
                url: '/play-words/prev-word',
                data: {id: '<?php echo $list_id; ?>'},
                success: function (data) {
                    // const parseData = JSON.parse(data);
                    return_ajax(data);


                }
            });
        })


        $("#tothebegin").click(function () {
            // $("span#itogo").empty();

            $.ajax({
                type: 'POST',
                url: '/play-words/to-the-begining',
                data: {id: '<?php echo $list_id; ?>'},
                success: function (data) {
                    // const parseData = JSON.parse(data);
                    return_ajax(data);


                }
            });
        })


        $("#learnanddel").click(function () {
            // $("span#itogo").empty();

            $.ajax({
                type: 'POST',
                url: '/play-words/learn-and-del',
                data: {id: '<?php echo $list_id; ?>'},
                success: function (data) {
                    // const parseData = JSON.parse(data);
                    return_ajax(data);


                }
            });
        })


        $("#mixandstart").click(function () {
            // $("span#itogo").empty();

            $.ajax({
                type: 'POST',
                url: '/play-words/mix-and-start',
                data: {id: '<?php echo $list_id; ?>'},
                success: function (data) {
                    // const parseData = JSON.parse(data);
                    return_ajax(data);


                }
            });
        })


    });


</script>